# use container
sudo: false

language: node_js

node_js:
  - '8'

cache:
  directories:
    - '$HOME/google-cloud-sdk'

before_deploy:
  # these steps are copied from 
  # https://www.drzon.net/posts/automatic-deployments-to-google-cloud-functions-with-travis-ci/

  # disable prompt when installing SDK
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # add gcloud to PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

  # is this needed?
  # - gcloud --quiet components update

  - openssl aes-256-cbc -K $encrypted_762e83343500_key -iv $encrypted_762e83343500_iv -in credentials/test-tridnguyen-com-2bb2099dfede.json.enc -out credentials/test-tridnguyen-com-2bb2099dfede.json -d
  - gcloud auth activate-service-account --key-file credentials/test-tridnguyen-com-2bb2099dfede.json
  - gcloud config set project test-tridnguyen-com

deploy:
  - provider: script
    script:
      - gcloud beta functions deploy get --stage-bucket test-tridnguyen-com --trigger-http
      - gcloud beta functions deploy set --stage-bucket test-tridnguyen-com --trigger-http
      - gcloud beta functions deploy del --stage-bucket test-tridnguyen-com --trigger-http
    skip_cleanup: true
    on:
      branch: master
